import React, { useState } from 'react';
import { SAMPLE_FARM_REPORT } from '../data/mockAnalytics';
import { DemoBadge } from '../components/common/DemoBadge';
import confetti from 'canvas-confetti';
import {
  FileCheck2,
  Download,
  Printer,
  Sparkles,
  CheckCircle2,
  AlertTriangle,
  Database,
  Cpu,
  Layers,
  Calendar,
  MapPin,
  RefreshCw,
} from 'lucide-react';

export const ReportsPage: React.FC = () => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState(false);
  const report = SAMPLE_FARM_REPORT;

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      confetti({
        particleCount: 60,
        spread: 70,
        origin: { y: 0.6 },
        colors: ['#059669', '#10B981', '#34D399', '#F59E0B'],
      });
    }, 800);
  };

  const handleDownload = () => {
    setDownloadSuccess(true);
    // Create and download a realistic agronomic report summary markdown/text
    const textContent = `
======================================================
AGRISENSE AI — COMPREHENSIVE FARM INTELLIGENCE REPORT
Generated on: ${report.generatedDate}
Report Reference: ${report.id}
======================================================

FARM OVERVIEW:
- Farm Facility: ${report.farmName}
- Principal Agronomist / Farmer: ${report.farmerName}
- Location: ${report.location}
- Total Monitored Acreage: ${report.totalAcreage} Hectares
- Overall Plant Health Index: ${report.overallHealthScore}%
- Predicted Total Biomass Yield: ${report.predictedTotalYield}

PRIMARY FIELD ALERTS:
${report.primaryAlerts.map((a, i) => `[${i + 1}] ${a}`).join('\n')}

RECENT FOLIAR PATHOLOGY ANALYSES:
${report.recentAnalyses
  .map(
    (a) =>
      `• Crop: ${a.crop} | Finding: ${a.disease} | Confidence: ${a.confidence}% | Status: ${a.status} (${a.date})`
  )
  .join('\n')}

RAG VECTOR SOURCES GROUNDING:
- Total authoritative documents retrieved: ${report.ragSourcesCount}
- Knowledge base: ICAR, FAO, University Extension Advisories

AI ADVISORY EXECUTIVE SUMMARY:
"${report.aiAdvisorySummary}"

======================================================
DISCLAIMER: Generated by AgriSense AI Demonstration System.
Field treatments should be confirmed with local agricultural officers.
======================================================
    `.trim();

    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AgriSense_AI_Report_${report.id}.txt`;
    link.click();
    URL.revokeObjectURL(url);

    setTimeout(() => setDownloadSuccess(false), 3000);
  };

  return (
    <div className="min-h-screen bg-[#F7F5F0] py-12">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-10">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 pb-6 border-b border-stone-200">
          <div>
            <div className="inline-flex items-center gap-2 mb-2">
              <DemoBadge variant="pill" />
            </div>
            <h1 className="text-3xl sm:text-4xl font-black text-stone-900 tracking-tight">
              AI Farm Report Generator
            </h1>
            <p className="text-sm text-stone-600 mt-1">
              Synthesize multi-spectral health logs, disease scans, yield projections, and RAG evidence into an official report.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-3">
            <button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl font-bold text-white bg-emerald-700 hover:bg-emerald-800 disabled:opacity-60 shadow-md shadow-emerald-950/15 transition-all text-xs sm:text-sm"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin text-emerald-200" />
                  <span>Synthesizing...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-emerald-200" />
                  <span>Generate AI Report</span>
                </>
              )}
            </button>

            <button
              onClick={handleDownload}
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl font-bold text-stone-800 bg-white hover:bg-stone-50 border border-stone-200 shadow-xs transition-colors text-xs sm:text-sm"
            >
              <Download className="w-4 h-4 text-emerald-700" />
              <span>{downloadSuccess ? 'Downloaded!' : 'Download Report'}</span>
            </button>
          </div>
        </div>

        {/* Printable/Preview Report Document Card */}
        <div className="bg-white rounded-3xl p-6 sm:p-10 border border-stone-200 shadow-xl shadow-stone-900/5 space-y-8">
          {/* Report Top Banner */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b-2 border-stone-100">
            <div>
              <div className="flex items-center gap-2">
                <span className="w-3 h-3 rounded-full bg-emerald-600" />
                <span className="text-xs font-mono font-bold text-emerald-800 uppercase tracking-widest">
                  OFFICIAL AGRONOMIC AUDIT // DEMO
                </span>
              </div>
              <h2 className="text-2xl font-black text-stone-900 tracking-tight mt-1">
                {report.farmName}
              </h2>
              <div className="flex flex-wrap items-center gap-3 text-xs text-stone-500 mt-1">
                <span className="flex items-center gap-1">
                  <MapPin className="w-3.5 h-3.5 text-stone-400" /> {report.location}
                </span>
                <span>•</span>
                <span className="flex items-center gap-1">
                  <Calendar className="w-3.5 h-3.5 text-stone-400" /> {report.generatedDate}
                </span>
                <span>•</span>
                <span className="font-mono text-emerald-700 font-bold">{report.id}</span>
              </div>
            </div>

            <div className="text-left sm:text-right">
              <span className="text-xs text-stone-500 font-medium block">Lead Farmer</span>
              <strong className="text-stone-900 text-sm font-bold block">{report.farmerName}</strong>
              <span className="text-xs text-emerald-700 font-bold">{report.totalAcreage} Total Hectares</span>
            </div>
          </div>

          {/* Key Metrics Summary */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="p-4 rounded-2xl bg-stone-50 border border-stone-200/80 text-center">
              <span className="text-xs font-bold text-stone-500 uppercase">Crop Health</span>
              <div className="text-2xl font-black text-emerald-700 mt-0.5">{report.overallHealthScore}%</div>
              <span className="text-[11px] text-emerald-600 font-medium">Optimal Vigor</span>
            </div>

            <div className="p-4 rounded-2xl bg-stone-50 border border-stone-200/80 text-center">
              <span className="text-xs font-bold text-stone-500 uppercase">Disease Risk</span>
              <div className="text-2xl font-black text-amber-700 mt-0.5">Low-Mod</div>
              <span className="text-[11px] text-amber-600 font-medium">Block A Alert</span>
            </div>

            <div className="p-4 rounded-2xl bg-stone-50 border border-stone-200/80 text-center">
              <span className="text-xs font-bold text-stone-500 uppercase">Predicted Yield</span>
              <div className="text-2xl font-black text-emerald-700 mt-0.5">4.2 t/ac</div>
              <span className="text-[11px] text-stone-500 font-medium">+8.5% Above Avg</span>
            </div>

            <div className="p-4 rounded-2xl bg-stone-50 border border-stone-200/80 text-center">
              <span className="text-xs font-bold text-stone-500 uppercase">RAG Sources</span>
              <div className="text-2xl font-black text-teal-700 mt-0.5">{report.ragSourcesCount}</div>
              <span className="text-[11px] text-teal-600 font-medium">Verified Citations</span>
            </div>
          </div>

          {/* Primary Alerts Section */}
          <div>
            <h3 className="text-sm font-bold uppercase tracking-wider text-stone-500 mb-3 flex items-center gap-1.5">
              <AlertTriangle className="w-4 h-4 text-amber-600" />
              Primary Field Alerts & Observations
            </h3>
            <div className="space-y-2">
              {report.primaryAlerts.map((alert, i) => (
                <div
                  key={i}
                  className="flex items-start gap-3 p-3.5 rounded-2xl bg-amber-50/70 border border-amber-200/80 text-xs text-amber-950 font-medium leading-relaxed"
                >
                  <span className="w-5 h-5 rounded-md bg-amber-200 text-amber-900 flex items-center justify-center font-bold text-[10px] shrink-0 mt-0.5">
                    0{i + 1}
                  </span>
                  <span>{alert}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Recent Foliar Pathology Analyses */}
          <div>
            <h3 className="text-sm font-bold uppercase tracking-wider text-stone-500 mb-3 flex items-center gap-1.5">
              <Cpu className="w-4 h-4 text-emerald-600" />
              Recent Foliar Pathology Logs
            </h3>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead className="bg-stone-50 text-stone-600 uppercase font-mono text-[11px]">
                  <tr>
                    <th className="p-3">Crop</th>
                    <th className="p-3">Predicted Pathology</th>
                    <th className="p-3">ML Confidence</th>
                    <th className="p-3">Action Status</th>
                    <th className="p-3">Timestamp</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-stone-100">
                  {report.recentAnalyses.map((row, idx) => (
                    <tr key={idx}>
                      <td className="p-3 font-bold text-stone-900">{row.crop}</td>
                      <td className="p-3 text-stone-800">{row.disease}</td>
                      <td className="p-3 font-mono font-bold text-emerald-700">{row.confidence}%</td>
                      <td className="p-3 font-semibold text-stone-600">{row.status}</td>
                      <td className="p-3 text-stone-400">{row.date}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* AI Advisory Summary */}
          <div className="p-6 rounded-2xl bg-emerald-50/60 border border-emerald-200/80">
            <div className="flex items-center gap-2 text-xs font-bold text-emerald-900 uppercase tracking-wider mb-2">
              <Sparkles className="w-4 h-4 text-emerald-700" />
              <span>GenAI Advisory Synthesis</span>
            </div>
            <p className="text-xs sm:text-sm text-stone-700 leading-relaxed italic">
              "{report.aiAdvisorySummary}"
            </p>
          </div>

          {/* Footer Disclaimer */}
          <div className="pt-4 border-t border-stone-200 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-stone-400">
            <span>Verified by AgriSense AI RAG Pipeline • Powered by ICAR Extension Manuals</span>
            <span className="font-mono text-emerald-700 font-semibold">STATUS: VERIFIED DEMO REPORT</span>
          </div>
        </div>
      </div>
    </div>
  );
};
